### ISSUE TITLE
Questions about distribution align codes

### ISSUE THREAD

**Issue by QiushiYang** [salesforce/CoMatch#3]
Thanks for sharing your clean codes. 
While I find that the codes of distribution alignment (DA) only calculate:
 q = Norm(q/mean(p(y))), 
without multiplying labeled data distribution p(y) and further sharpening, which seems not same as the DA introduced in ReMixMatch. Wonder why don't use the standard DA to train models? Is the simple way you used better for SSL models' performance?

**Comment by LiJunnan1992** [comment]
Hi, apologies for the late reply.
I found this simpler DA to have the same performance as the one used for ReMixMatch.
