### ISSUE TITLE
Would you like to share your traning/testing log for 1% and 10% imagenet setting ?

### ISSUE THREAD

**Issue by mingkai-zheng** [salesforce/CoMatch#4]

**Comment by LiJunnan1992** [comment]
Sure. Would you mind to send me an email and I can reply to you with the log files? It is too long to be shared here.

**Comment by mingkai-zheng** [comment]
It's okay, I have already get the training logs by running this code, thank you

**Comment by QiushiYang** [comment]
> 

Would you like to share the ImageNet training and testing logs for 1% and 10% with me? My email address is: mryangqiushi@gmail.com. Many thanks.

**Comment by beandkay** [comment]
@LiJunnan1992  can you also email me the logs, my email is tinyswish@gmail.com, thank you
